project:
  type: website
  preview:
    port: 4001
    browser: false

execute:
  freeze: auto
  cache: true

website:
  title: "HoTT.jpeg"
  site-url: https://desyncthethird.github.io/HoTT
  description: "not Vikraman's personal website"
  favicon: favicon.svg
  search:
    location: navbar
    type: overlay
    keyboard-shortcut: ["?", "H"]
  # navigation
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/desyncthethird/HoTT
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  # footer
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"

format:
  html:
    # styling
    theme:
      light: theme/theme-light.scss
      dark: theme/theme-dark.scss
    respect-user-color-scheme: true
    # layout
    title-block-banner: true
    toc: true
    anchor-sections: true
    smooth-scroll: true
    # maths
    html-math-method:
      method: mathjax
      url: https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
