---
title: Homotopy Levels
subtitle: AAAAAAAAAAAAAAAA
date: today
---

::: hidden
\newcommand{\type}[1]{\mathsf{#1}}
\newcommand{\term}[1]{\operatorname{\mathsf{#1}}}

\newcommand{\tpt}[2]{\term{transport}({#1,#2})}
\newcommand{\tp}[1]{{#1}^{\ast}}

\newcommand{\id}{\term{id}}
\newcommand{\refl}[1][]{\term{refl}_{#1}}

\newcommand{\yo}{\mathop{よ}}

\newcommand{\defeq}{\stackrel{\triangle}{=}}

\newcommand{\Aut}{\operatorname{Aut}}
\newcommand{\BAut}{\operatorname{BAut}}

\require{bussproofs}

{{< include vc-hott.sty >}}

:::



::: {def-hlevel}

A type $A$ is *contractible* if there exists a *centre of contraction* $c:A$ such that for every term $x:A$, $c=_Ax$:
\begin{equation*}
    \textsf{isContra}(A):=\sum_{c:A}\prod_{x:A}c=_Ax
\end{equation*}

We define the *homotopy level* of a type as follows:
\begin{align*}
    \textsf{is-($-2$)-type}(A)&:=\textsf{isContra}(A)\\
    \textsf{is-($n+1$)-type}(A)&:=\prod_{x,y:A}\textsf{is-$n$-type}(x=_Ay)
\end{align*}
That is, a type is a ($-2$)-type if it is contractible, and is an $n$-type if all of its equality types are ($n-1$)-types.

We alias some common homotopy levels as follows:
\begin{equation*}
    \textsf{isProp}(A)&:=\textsf{is-($-1$)-type}(A)\\
    \textsf{isSet}(A)&:=\textsf{is-$0$-type}(A)
\end{equation*}

:::

::: {lem-hlevel-prop}

For any type $A$, $\textsf{is-$n$-type}(A)$ is a proposition for all $n$.
\begin{equation*}
    \mathsf{isProp}\bigl(\textsf{is-$n$-type}(A)\bigr)
\end{equation*}

:::

::: {lem-hlevel-cumulative}

Homotopy levels are cumulative. That is:

\begin{equation*}
    \textsf{is-$n$-type}(A)\rightarrow\textsf{is-($n+1$)-type}(A)
\end{equation*}

:::


::: {lem-hlevels-misc}

\begin{itemize}
    \item If $A:\mathcal{U}$ is an $n$-type, and $A\simeq B$, then $B$ is an $n$-type.
    
    \item For any $A:\mathcal{U}$, its $n$-truncation $\|A\|_n$ is an $n$-type. In particular, if $B$ is an $n$-type, then
    \begin{equation*}
        (A\rightarrow B)\simeq\bigl(\|A\|_n\rightarrow B\bigr)
    \end{equation*}
    
    \item Let $B:\mathcal{U}$ be an $n$-type. Then, for any $A:\mathcal{U}$, the function type
    \begin{equation*}
        A\rightarrow B
    \end{equation*}
    is an $n$-type.

    \item Let $B:A\rightarrow\mathcal{U}$ be a type family with $B(a)$ an $n$-type for all $a:A$. Then, the dependent function type
    \begin{equation*}
        \prod_{a:A}B(a)
    \end{equation*}
    is an $n$-type.

    \item Let $A,B:\mathcal{U}$ be an $n$-type and $m$-type, respectively. Then, the product type
    \begin{equation*}
        A\times B
    \end{equation*}
    is an $\max(n,m)$-type.

    \item Let $A:\mathcal{U}$ be an $n$-type and $B:A\rightarrow\mathcal{U}$ be a type family with $B(a)$ an $m$-type for all $a:A$. Then, the dependent pair type
    \begin{equation*}
        \sum_{a:A}B(a)
    \end{equation*}
    is an $\max(n,m)$-type.

    \item Let $B:\mathcal{U}$ be an $n$-type. Then, for any function $f:A\rightarrow B$, every homotopy fibre
    \begin{equation*}
        \textsf{fib}_f(b):=\sum_{a:A}f(a)=_Bb
    \end{equation*}
    is an $n$-type if and only if $A$ is an $n$-type.
\end{itemize}

:::















::: {def-aut}

Given a type $T$, we define the type $\Aut(T)$ of self equivalences of $T$ as:
\begin{align*}
    \Aut(T)&:=T\simeq T\\
    &\hphantom{:}=\sum_{f:T\rightarrow T}\mathsf{isEquiv}(f)%\\
    % &\hphantom{:}=\sum_{f:T\rightarrow T}\prod_{b:T}\mathsf{isContra}\sum_{a:T}f(a)=_Tb\\
    % &\hphantom{:}=\sum_{f:T\rightarrow T}\prod_{b:T}\sum_{c:\sum_{a:T}f(a)=_Tb}\prod_{p:\sum_{a:T}f(a)=_Tb}c=_{\sum_{a:T}f(a)=_Tb}p
\end{align*}

:::


::: {def-baut}

Given a type $T$, we define the type $\BAut(T)$ as:
\begin{equation*}
    \BAut(T):=\sum_{X:\mathcal{U}}\|X=T\|_{-1}
\end{equation*}

:::


::: {thm-aut-hlevel}

If $T$ is an $n$-type, then $\Aut(T)$ is also an $n$-type.

:::


::: proof

Let $\langle f,p\rangle,\langle g,q\rangle:\Aut(T)$.

Suppose $T$ is contractible. Then,
\begin{align*}
    \bigl(\langle f,p\rangle=\langle g,q\rangle\bigr)\simeq(P:f=g)\times\bigl(P_\ast(p)=q\bigr)
\end{align*}
By assumption, $T$ is contractible, so $T\rightarrow T$ is contractible, and in particular, the identity type $f=g$ is contractible. Since $P_\ast(p)$ and $q$ are propositions, their equality type is contractible. Hence, $\Aut(T)$ is contractible.

Otherwise, suppose $T$ is an $n$-type for $n\geq-1$. Since $\mathsf{isEquiv}(f)$ is a proposition for all $f:T\rightarrow T$, the homotopy level of the dependent pair $\sum_{f:T\rightarrow T}\mathsf{isEquiv}(f)$ is the maximum of $-1$ and the homotopy level of $T\rightarrow T$, the latter of which is the homotopy level of the codomain $T$. Since $n\geq-1$, $\max(-1,n)=n$, and $\Aut(T)$ is an $n$-type.

:::




::: {thm-baut-hlevel}

If $T$ is an $n$-type, then $\BAut(T)$ is an ($n+1$)-type.

:::


::: proof

Let $\langle X,p\rangle,\langle Y,q\rangle:\BAut(T)$. Then,
\begin{equation*}
    \bigl(\langle X,p\rangle=\langle Y,q\rangle\bigr)\simeq\sum_{P:X=Y}P_\ast(p)=q
\end{equation*}
Since $P_\ast(p)$ and $q$ are propositions, their equality is contractible, so the homotopy level of this dependent pair is the level of $X=Y$.

Since being an $n$-type is a proposition, we may assume $X\simeq T$ and $Y\simeq T$. Since equivalences preserve homotopy level, $X$ and $Y$ are $n$-types. Combining the equivalences also yields $X\simeq Y$. Since $X,Y$ are $n$-types, $X\simeq Y$ is an $n$-type, and thus by univalence, $(X=Y)\simeq(X\simeq Y)$ is an $n$-type. Hence $\BAut(T)$ is an ($n+1$)-type.

:::



::: {def-loop}

Given a pointed type $(A,a)$, we define the *loop space* $\Omega A$ as the equality type:
\begin{equation*}
    \Omega A:=(a=a)
\end{equation*} 

:::



::: {thm-loop-deloop}
For any $T$, 
\begin{equation*}
    \Omega\BAut(T)\simeq\Aut(T)
\end{equation*}
where $\BAut(T)$ is pointed at $|\refl|$.

:::


::: proof

By the definition of a loop space,
\begin{equation*}
    \Omega\BAut(T):=\bigl((T,|\refl|)=(T,|\refl|)\bigr)=\sum_{P:T=T}P_\ast(|\refl|)=|\refl|
\end{equation*}
Since this is an equality of propositions, this sum is equivalent to $T=T$. By univalence, $(T=T)\simeq(T\simeq T)=:\Aut(T)$.

:::


