---
title: Yoneda
subtitle: <Subtitle>
date: today
---

::: hidden
\newcommand{\type}[1]{\mathsf{#1}}
\newcommand{\term}[1]{\operatorname{\mathsf{#1}}}

\newcommand{\tpt}[2]{\term{transport}({#1,#2})}

\newcommand{\tp}[1]{{#1}_{\ast}}
\newcommand{\id}[1][]{\term{id}_{#1}}
\newcommand{\refl}[1][]{\term{refl}_{#1}}

\newcommand{\yo}{\mathop{よ}}

\newcommand{\defeq}{\stackrel{\triangle}{=}}

\require{bussproofs}
:::

::: {#def-natural-transformation}
A **natural transformation** between two type families $F,G:A\rightarrow\mathcal{U}$ is a family of maps
$$
    \alpha:(x:A)\rightarrow(F(x)\rightarrow G(x))
$$

We denote the type of natural transformations between $F$ and $G$ by $\mathrm{Nat}(F,G)$.
:::

::: {#def-yoneda-embedding}
The Yoneda embedding $よ_A:A\rightarrow(A\rightarrow\mathcal{U})$ is defined by
$$
    よ_A(a):\equiv\lambda x.(a=x).
$$
:::

::: {#thm-yoneda}
For any type family $F:A\rightarrow\mathcal{U}$, the map
$$
\begin{align*}
    f:\type{Nat}(よ_A(a),F)&\rightarrow F(a)\\
    \alpha&\mapsto\alpha(a,\refl[a])
\end{align*}
$$

is an equivalence.
:::

::: proof
We construct the inverse map
$$
\begin{align*}
    g:F(a)&\rightarrow\type{Nat}(よ_A(a),F)\\
    u&\mapsto J\bigl(\lambda(x:A)\lambda(p:x=_Aa).F(x),u\bigr)
\end{align*}
$$

We show $g\circ f=\id[\type{Nat}(よ_A(a),F)]$. By $\term{funext}$, it is sufficient to show:
$$
    \bigl(\alpha:\type{Nat}(よ_A(a),F)\bigr)\rightarrow (g\circ f)(\alpha)=\alpha
$$

but $\alpha:(x:A)\rightarrow よ_A(a)(x)\rightarrow F(x)$ is a (higher) function, so by two more applications of $\term{funext}$, we need:
$$
    \bigl(\alpha:\type{Nat}(よ_A(a),F)\bigr)\rightarrow(x:A)\rightarrow(p:a=_Ax)\rightarrow\bigl(g\circ f(\alpha)\bigr)(x,p)=\alpha(x,p)
$$

By based path induction on $p$, it suffices to construct the method $c_0:\bigl(g\circ f(\alpha)\bigr)(a,\refl[a])=\alpha(a,\refl[a])$; but this equality is judgemental:
$$
\begin{align*}
    g\bigl(f(\alpha)\bigr)(a,\refl[a])&\equiv J(\lambda x\lambda p.f(\alpha))(a,\refl[a])\\
    &\equiv\alpha(a,\refl[a])\tag{$J_\beta$}
\end{align*}
$$

So the overall proof term is given by:
$$
    \term{funext}\lambda\alpha.\term{funext}\term{funext}J\Bigl(\lambda x\lambda p.(g\circ f(\alpha)\bigr)(x)(p)=\alpha(x)(p),\refl[\alpha(a)(\refl[a])]\Bigr)
$$

To show $f\circ g=\id[F(a)]$, we again reduce by $\term{funext}$ to:
$$
    (x:A)\rightarrow f\circ g(x)=x
$$
$$
\begin{align*}
    (f\circ g)(u)&\equiv f\Bigl(J\bigl(\lambda x\lambda p.F(x),u\bigr)\Bigr)\\
    &\equiv\Bigl(J\bigl(\lambda x\lambda p.F(x),u\bigr)\Bigr)(a,\refl[a])\\
    &\equiv u\tag{$J_\beta$}
\end{align*}
$$
so the proof term is:
$$
    \term{funext}(\refl[u])
$$

:::







# Introduction

::: {.column-margin}
This is another prooftree but in the margin.
$$
\begin{prooftree}
  \AxiomC{ $P$ }
  \AxiomC{ $P \to Q$ }
  \BinaryInfC { $Q$ }
\end{prooftree}
$$
:::


